language: node_js
node_js:
  - '12'
  - '10'
  - '8'
  - '6'
before_install:
  - npm install -g yarn@1.10.1 # nyc does not run properly with newer yarn for some reason
install:
  - yarn install --pure-lockfile
script:
  - yarn run test:ci
